# SPDX-FileCopyrightText: 2026 Darshan Phaldesai <dev.darshanphaldesai@gmail.com>
# SPDX-License-Identifier: MPL-2.0

[workspace]
resolver = "3"
members = [
    "cxx-kde-frameworks",

    "examples/simplemdviewer",
    "examples/kapp"
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
cxx = "1.0.192"
# cxx-qt = "0.8.0"
# cxx-qt-lib = { features = ["qt_full"], version = "0.8.0" }
# cxx-qt-lib-extras = { version = "0.8.0" }
qtbridge = { git = "https://github.com/qt/qtbridge-rust.git" }
qtbridge-type-lib = { git = "https://github.com/qt/qtbridge-rust.git" }
cxx-kde-frameworks = { path = "cxx-kde-frameworks" }

cc = "1"
cmake-package = "0.1.10"
cxx-build = { version = "1.0.158", features = [ "parallel" ] }
# cxx-qt-build = { features = ["link_qt_object_files"], version = "0.8.0" }
qtbridge-build-utils = { git = "https://github.com/qt/qtbridge-rust.git" }
