# SPDX-FileCopyrightText: 2024 Darshan Phaldesai <dev.darshanphaldesai@gmail.com>
# SPDX-License-Identifier: MPL-2.0

[package]
name = "cxx-kde-frameworks"
version = "0.1.0"
edition.workspace = true
links = "cxx-kde-frameworks"

[dependencies]
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true }
cxx-qt-lib-extras = { workspace = true }
qtbridge = { workspace = true }
qtbridge-type-lib = { workspace = true }

[build-dependencies]
# cc = { workspace = true }
cmake-package = { workspace = true }
# cxx-build = { workspace = true }
cxx-qt-build = { workspace = true }
# qtbridge-build-utils = { workspace = true }
