[package]
name = "cxx-kf6"
version = "0.1.0"
edition = "2021"


[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true
cxx-qt-lib-headers.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true
cxx-kf6-build.workspace = true